language: java
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
- mvn package -Dmaven.test.skip=true
addons:
  ssh_known_hosts:
  - 39.108.173.101
before_install:
- openssl aes-256-cbc -K $encrypted_e111a0414035_key -iv $encrypted_e111a0414035_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- cd ~/travis-ci/
- git pull
- mvn package