language: java
jdk:
    - oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
- mvn package -Dmaven.test.skip=true
after_script:
  - pwd
addons:
  ssh_known_hosts:
  - 39.108.173.101 #受信主机，你的Linux服务器ip
before_install:
- openssl aes-256-cbc -K $encrypted_900d58bc5f09_key -iv $encrypted_900d58bc5f09_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
- ssh travis@39.108.173.101 -o StrictHostKeyChecking=no   #使用ssh连接服务器